version: '3.8'
services:
  app-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=William316
    restart: always
    ports:
      - 8000:8000
    container_name: db
    volumes:
      - /data/mysql/log:/var/log/mysql
      - /data/mysql/data:/var/lib/mysql
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        server-app: v1
    depends_on:
      - app-db
    container_name: server-app
    network_mode: "container:db"
