version: '3.3'
services:
  app-db:
    image: mysql:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD=William316
    network_mode: host
    restart: always
    container_name: db
    volumes:
      - /data/mysql/log:/var/log/mysql
      - /data/mysql/data:/var/lib/mysql
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        server-app: v1
    depends_on:
      - app-db
    network_mode: host
    container_name: server-app
    volumes:
      - /data/media:/djangoForum/media
    restart: always
