# Generated by Django 4.2.1 on 2023-05-31 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField(default="", max_length=20)),
                ("user_code", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("Email", models.CharField(blank=True, max_length=30, null=True)),
                ("birthday", models.CharField(default="2000-00-00", max_length=20)),
                ("sex", models.BooleanField(default=True)),
                ("Follower", models.IntegerField(blank=True, default=0, null=True)),
                ("SelfIntro", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "imageSrc",
                    models.ImageField(default="avatar.jpg", upload_to="photos"),
                ),
                (
                    "UserName",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_name",
                        to="forumApp.login",
                    ),
                ),
                (
                    "blocked_users",
                    models.ManyToManyField(
                        related_name="blocked_by", to="forumApp.user"
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        related_name="followers", to="forumApp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, default="校园新闻", max_length=30, null=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("text", models.TextField()),
                (
                    "picSrc1",
                    models.ImageField(blank=True, null=True, upload_to="photos"),
                ),
                (
                    "picSrc2",
                    models.ImageField(blank=True, null=True, upload_to="photos"),
                ),
                (
                    "picSrc3",
                    models.ImageField(blank=True, null=True, upload_to="photos"),
                ),
                (
                    "picSrc4",
                    models.ImageField(blank=True, null=True, upload_to="photos"),
                ),
                (
                    "picSrc5",
                    models.ImageField(blank=True, null=True, upload_to="photos"),
                ),
                (
                    "picSrc6",
                    models.ImageField(blank=True, null=True, upload_to="photos"),
                ),
                (
                    "picSrc7",
                    models.ImageField(blank=True, null=True, upload_to="photos"),
                ),
                (
                    "picSrc8",
                    models.ImageField(blank=True, null=True, upload_to="photos"),
                ),
                (
                    "picSrc9",
                    models.ImageField(blank=True, null=True, upload_to="photos"),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("like", models.IntegerField(default=0)),
                ("comment_num", models.IntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_user",
                        to="forumApp.user",
                    ),
                ),
                (
                    "who_favorite",
                    models.ManyToManyField(
                        related_name="favorite_posts", to="forumApp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("detail", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=30)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications2",
                        to="forumApp.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications1",
                        to="forumApp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="forumApp.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="forumApp.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversation",
            name="participant1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations1",
                to="forumApp.user",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="participant2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations2",
                to="forumApp.user",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_comment",
                        to="forumApp.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forumApp.user"
                    ),
                ),
            ],
        ),
    ]
