# Generated by Django 4.2.1 on 2023-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forumApp", "0002_post_video_alter_post_picsrc1_alter_post_picsrc2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favorite_num",
            field=models.IntegerField(default=0),
        ),
    ]
