# Generated by Django 4.2.1 on 2023-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forumApp", "0003_post_favorite_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="who_like",
            field=models.ManyToManyField(related_name="like_posts", to="forumApp.user"),
        ),
    ]
